config/routes.rb
ClassicLookSalon::Application.routes.draw do
  root :to => 'home#index'

  get '/services' => 'home#services'
  get '/directions' => 'home#directions'
  get '/contact_us' => 'home#contact_us'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def services

  end

  def directions

  end

  def contact_us

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_hours.haml
.section
  .title Our Hours
  .content
    .row.bold
      .day Day
      .opening Opening
      .closing Closing
    .row
      .day Monday
      .opening Closed
      .closing Closed
    .row
      .day Tuesday
      .opening 9:30 am
      .closing 2:00 pm
    .row
      .day Wednesday
      .opening 9:30 am
      .closing 7:00 pm
    .row
      .day Thursday
      .opening 9:30 am
      .closing 6:00 pm
    .row
      .day Friday
      .opening 9:30 am
      .closing 5:00 pm
    .row
      .day Saturday
      .opening 9:30 am
      .closing 5:00 pm
    .row
      .day Sunday
      .opening Closed
      .closing Closed

app/views/home/contact_us.haml
.main
  .title Contact The Classic Look
  .model= image_tag '/assets/model.png', :alt => 'Hair Model'
  .text
    .section
      .title Contact Us
      .content
        Please call us during business hours regarding any question, concerns,
        or to schedule an appointment with our friendly, experienced and talented staff.
        Our phone number is
        .phone
          %strong (973) 857-4353

    = render 'home/hours'

app/views/home/directions.haml
.main
  .title.no-border Directions to The Classic Look
  = render 'home/map'

app/views/home/index.haml
.main
  .title The Classic Look Nail and Hair Salon
  .model= image_tag '/assets/model.png', :alt => 'Hair Model'
  .text
    .section
      .title The Goal of Creating Beauty
      .content
        The Classic Look is a full service salon combining state-of-the-art American
        cosmetology techniques with classic European hair, nail, and skincare secrets.
        Our staff, a seamless blend of European and American professionals, provide our
        clients with a myriad of services with a distinct cosmopolitan flair.
    .section
      .title Beauty Begins with a Blank Canvas
      .content
        Steeped in the European belief that all people are beautiful and beauty
        begins with healthy glowing skin, The Classic Look Salon offers the services of
        European trained beauticians. Most woman have the been programmed to think they
        need make-up in order to enhance their beauty, but with the proper skincare,
        make-up is an unnecessary expense and additive. The best testament to this theory
        is the healthy, radiant skin of our staff who exude youthful energy.

    .section
      .title A Woman's Crowning Glory
      .content
        The staff at The Classic Look Salon are true artists. In the hands of these
        trained professionals, your hair becomes everything you knew it could be.
        Their secret? Communicating with each client, discussing options, taking lifestyle
        and desires into consideration before a single strand is even snipped. Once they
        work their magic, you will be well on your way to becoming a new you.

app/views/home/services.haml
.main
  .title Services at The Classic Look
  .model= image_tag '/assets/model.png', :alt => 'Hair Model'
  .text
    = render 'services/hair_care'
    = render 'services/nail_care'
    = render 'services/waxing'
    = render 'services/skin_care'

app/views/layouts/_footer.haml
%footer
  Made by
  .dev-name= link_to 'Phillip Boksz', 'http://www.phillipboksz.com', :target => '_blank'

app/views/layouts/_header.haml
%header
  .left-side
    .main-title
      The Classic Look

    .links
      .link= link_to 'Home', root_path
      .link= link_to 'Services', services_path
      .link= link_to 'Directions', directions_path
      .link= link_to 'Contact Us', contact_us_path

  .right-side
    .address
      .street 146 Bloomfield Ave
      .city-state Verona, NJ 07044
      .phone (973) 857-4353

app/views/layouts/application.haml
!!!

%html
  %head
    %title The Classic Look | Verona, NJ | Hair, Nails, Beauty
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

    // javascript for google analytics
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-22236727-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

  %body
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'

app/views/services/_hair_care.haml
.section
  .title Hair Care
  .content
    .row
      .desc Shampoo, Cut Style
      .price $50+
    .row
      .desc Hair Styling
      .price $30+
    .row
      .desc Special Evening Style
      .price $60+
    .row
      .desc Bridal Evening Style
      .price $70+
    .row
      .desc Men's Haircut
      .price $25
    .row
      .desc Kid's Haircut
      .price $25
    .row
      .desc Perms
      .price $75+
    .row
      .desc Single Process Color
      .price $60
    .row
      .desc Full Foil Highlights or Lowlights
      .price $80+
    .row
      .desc Partial Foil Highlights or Lowlights
      .price $60+
    .row
      .desc Hair and Scalp Wellness Treatment
      .price $20

app/views/services/_nail_care.haml
.section
  .title Nail Care
  .content
    .row
      .desc Manicure
      .price $14
    .row
      .desc Wraps
      .price $50
    .row
      .desc Tips and Wraps
      .price $60
    .row
      .desc Fills-in
      .price $35
    .row
      .desc Pedicure
      .price $29
    .row
      .desc Hand Paraffin
      .price $8

app/views/services/_skin_care.haml
.section
  .title Skin Care
  .content
    .row
      .desc European Facial
      .price $85
    .row
      .desc Deep Cleaning Facial
      .price $80
    .row
      .desc Microdermabrasion
      .price $120
    .row
      .desc Collagen Veil Mask
      .price $30

app/views/services/_waxing.haml
.section
  .title Waxing
  .content
    .row
      .desc Eyebrow
      .price $15
    .row
      .desc Lip
      .price $10
    .row
      .desc Chin
      .price $8
    .row
      .desc Forearms
      .price $15
    .row
      .desc Full Arms
      .price $30
    .row
      .desc Underarms
      .price $15
    .row
      .desc Back
      .price $45
    .row
      .desc Half Legs
      .price $25
    .row
      .desc Full Legs
      .price $50
    .row
      .desc Bikini Line
      .price $25